pub static FRUITS: &[&str] = &[
    "apple",
    "apricot",
    "artichoke",
    "asparagus",
    "avocado",
    "banana",
    "beet",
    "blackberry",
    "blueberry",
    "broccoli",
    "brussels sprout",
    "cabbage",
    "carrot",
    "cauliflower",
    "celery",
    "cherry",
    "coconut",
    "corn",
    "cranberry",
    "cucumber",
    "date",
    "eggplant",
    "elderberry",
    "fig",
    "gooseberry",
    "grape",
    "grapefruit",
    "green bean",
    "green pepper",
    "guava",
    "honeydew",
    "kale",
    "kiwi",
    "leek",
    "lemon",
    "lettuce",
    "lime",
    "lychee",
    "mango",
    "mushroom",
    "nectarine",
    "olive",
    "onion",
    "orange",
    "papaya",
    "pea",
    "peach",
    "pear",
    "persimmon",
    "pineapple",
    "plum",
    "pomegranate",
    "potato",
    "pumpkin",
    "quince",
    "radish",
    "raspberry",
    "red pepper",
    "spinach",
    "squash",
    "strawberry",
    "sweet potato",
    "swiss chard",
    "tangerine",
    "tomato",
    "turnip",
    "watermelon",
    "yam",
    "zucchini",
];
